### ISSUE TITLE
Code does not run and has errors

### ISSUE THREAD

**Issue by ghost** [viadee/magie#1]
hi, 

I am running the pipeline on eclipse and receive errors for all datasets.
<img width="691" alt="Screenshot 2020-07-01 at 12 24 25 PM" src="https://user-images.githubusercontent.com/64469406/86212515-d79af780-bb95-11ea-8b64-33dfa852b34a.png">

**Comment by fkoehne** [comment]
Thanks for your interest! Maybe @NoItAll can help you out? 
My first impression is, that this looks like java version or build tooling mismatch.

**Comment by ghost** [comment]
Thanks. Waiting for @NoItAll's response. Meanwhile could you also let me know if I can run this for my own dataset which I have in a csv file or it is custom built for the datasets provided ?

**Comment by fkoehne** [comment]
That should be possible with reasonable effort. We have not maintained this p.o.c. in a while, however. What is your context, i.e. what are you trying to do with it?

**Comment by NoItAll** [comment]
Hello @adityakumar04 ,
I just checked out the project on a new computer with a different IDE (Eclipse in this case): It runs without any problem.
Are you sure you have configured the project as a Maven project? `AnchorTabular` etc. are all classes which are retrieved from a separate project via Maven.
![image](https://user-images.githubusercontent.com/22979866/86237703-8b06ea80-bb9c-11ea-8678-5002108c625b.png)


Additionally, a snippet of the result of the invocation of the main: 
![image](https://user-images.githubusercontent.com/22979866/86237997-12ecf480-bb9d-11ea-9cca-6e5add61c526.png)

**Comment by NoItAll** [comment]
@adityakumar04 Using new datasets should be very easy: With the current AnchorTabular-approach, you would have to define the columns of your .csv (use `addIgnoredColumn` for columns you do not need) in the order given in the .csv.

Hopefully this is helpful.

**Comment by ghost** [comment]
Thanks, Could you point me to the section of code where we can make changes for csv.? Actually I am a python coder and I am looking to understand this so that I can convert this code to a python repo. Appreciate your help

**Comment by NoItAll** [comment]
A good idea is to look at any of the demo-classes in the validation-package (e.g. `AdultValidation`). 
`AnchorTabular anchorTabular = new AnchorTabular.Builder()
     .setDoBalance(false)
     .addColumn(DoubleColumn.fromStringInput("age"))
 ... 
     .addIgnoredColumn(DoubleColumn.fromStringInput("fnlwgt"))
...
     .build(ClassLoader.getSystemResourceAsStream("adult.data"), true, true);`
This part has to be substituted with your own data set and the columns of this data set.

Thereafter you can either construct your own pipeline or use one of the prefabricated ones (see the exemplary_pipeline-package), e.g. the `DirectMemeticMining`-pipeline-class. For this, again, you can look at the demo classes.
Could you still state what your specific use case here is? It is interesting for us to know what this software is used for :) It furthermore might be useful to distinguish if you do want to explain a machine-learning model or directly mine rules on the data set.

**Comment by ghost** [comment]
Thanks. My specific use case is to use it for explaining my machine learning models. I have compared various methods and till now MAGIC seems to be the best in giving a global explanation as well as providing deep understanding of features sets and their values in explaining predictions from a black box model. Does this help ?

**Comment by ghost** [comment]
Could you also explain me the meaning of the following statement in the output --- "Rule set with ID: 1, size: 2" and how to interpret multiple output sets

**Comment by NoItAll** [comment]
@adityakumar04 Is it for a university-project or in industry? :) 

Concerning the output: In this approach, for each label (the predicted categorical value), a separate rule set is created. The rule set with the ID 1 (check out which label-value this corresponds to) has two rules. 
Further information on the structure of the application should be given in the README of this repository :)

**Comment by ghost** [comment]
This is for my own personal experimentations in the space of Data science. Not affiliated to any industry or university. I will check out the readme. I am hoping we can collaborate further on this in case I need more help. Will this be the ideal channel to communicate with you for future queries?. Any help will be greatly appreciated.

**Comment by ghost** [comment]
On another note, I also looked at your anchorOnR repo. It is very good, However it is instance wise explanations. Do we also have a version which gives global explanations  and how different will it be from MAGIE ?

**Comment by NoItAll** [comment]
@adityakumar04 If there are any ambiguities in the README, or any suggestions or bug reports concerning the code, we will see to answer them as quick as possible and improve. For thorough discussions maybe @fkoehne can suggest further platforms? 

"Do we also have a version which gives global explanations and how different will it be from MAGIE ?" --> As far as I know (I have not checked in a while, though), MAGIE is _the_ open-source tool for generating global rule-based explanations. It tries to subsume multiple existing approaches for global rule-generation. Aside from MAGIE I could not find any (well-performing) existing tools for this. MAGIE, however, does not include non-rule-based visualizations.

In any case: Thank you very much for your interest!

**Comment by fkoehne** [comment]
This is probably the right place for further discussions (or pull requests :) ).

Cheers,
 Frank
