### ISSUE TITLE
Redundant conditions in rules

### ISSUE THREAD

**Issue by ghost** [viadee/magie#5]
Hi @NoItAll , 

I was running MAGIE using Iris dataset and noticed something  in the results which I would like to share with you.

Rule set with ID: 2, size: 1 |   |   |  
-- | -- | -- | --
RuleExplanation: |   |   |   |  
IF   petal_width IN {1.5<=petal_width<2.1, 2.1<=petal_width},
AND   petal_length IN {4.707<=petal_length<5.543, 5.543<=petal_length},

We can see that condition under petal width can be further cleaned to IF petal_width IN {1.5<=petal_width} or am I interpreting it wrongly ? If so, then can you guide me how to incorporate this in the code.

**Comment by NoItAll** [comment]
Hi @adityakumar04 ,
You are absolutely right here. The reason why it is "redundant" (I would phrase it as non-concise) is that for each of the categorical values you see MAGIE has created an index structure. So we cannot "join" these rules during the run time of the pipeline. However, for visualizing the rules you can join adjacent ranges for numeric features. 
I would again suggest you take a look at how these rules are visualized. You might want to check if a CategoricalFeature-instance in the antecedent of a rule is an instance of DiscretizedNumericFeature (https://github.com/viadee/magie/blob/master/src/main/java/de/viadee/xai/framework/data/Feature.java#L205) and, if this is the case, check whether the splitPoints are adjacent. 

Please let me know if this helped you.

**Comment by ghost** [comment]
Hi @NoItAll Thanks for the answer. I will look into it and update you.

**Comment by NoItAll** [comment]
I assume the issue is resolved.
